from agents.base import BaseAgent, AgentMessage, AgentStatus
from typing import Dict, Any
import json
from datetime import datetime


class PROpenerAgent(BaseAgent):
    """
    PR Opener Agent: Creates branch, commits fix, opens pull request.

    This agent:
    1. Creates a feature branch
    2. Applies the code diff
    3. Commits with conventional commit message
    4. Opens a PR with detailed description
    """

    def __init__(self):
        super().__init__(
            name="pr_opener",
            system_prompt="""
You are the PR Opener Agent in SwarmOps.

Your job:
1. Create a feature branch from main/master
2. Apply the code changes
3. Commit with a conventional commit message
4. Open a pull request with detailed description
5. Include test results and security audit in PR body

Rules:
- Use conventional commit format: "fix: description" or "feat: description"
- PR description must include:
  - Summary of the fix
  - Test results
  - Security audit results
  - Link to original issue
- Branch name: "fix/issue-{number}-description" or "feat/issue-{number}"
- Do NOT merge the PR automatically

Output format (JSON):
{
    "pr_url": "https://github.com/owner/repo/pull/143",
    "pr_number": 143,
    "branch": "fix/issue-42-typo-fix",
    "commit_sha": "abc123",
    "title": "fix: correct DATABASE_URL typo in config",
    "description": "Full PR description"
}
            """,
        )

    async def think(self, context: Dict[str, Any]) -> AgentMessage:
        """
        Create branch, commit, and open PR.

        Expected context:
        {
            "issue": {...},
            "repo": {...},
            "code_writer_output": {
                "diff": "...",
                "files_changed": [...],
                "summary": "..."
            },
            "test_runner_output": {
                "tests_passed": 47,
                "tests_failed": 0,
                "success": true
            },
            "security_auditor_output": {
                "passed": true,
                "findings": []
            }
        }
        """
        self.set_status(AgentStatus.THINKING, "Creating pull request")

        issue = context.get("issue", {})
        repo = context.get("repo", {})
        code_writer = context.get("code_writer_output", {})
        test_runner = context.get("test_runner_output", {})
        security = context.get("security_auditor_output", {})

        # TODO: Call GitHub API to create branch, commit, and PR
        # For now, simulate PR creation

        issue_number = issue.get("number", 0)
        issue_title = issue.get("title", "Fix")

        # Generate branch name
        branch_name = f"fix/issue-{issue_number}-swarmops"

        # Generate PR title
        pr_title = f"fix: {issue_title.lower()[:50]}"

        # Generate PR description
        pr_description = f"""## Summary
Automatically generated fix for issue #{issue_number}.

## Changes
{code_writer.get("summary", "No summary provided")}

## Files Modified
{chr(10).join(f"- {f}" for f in code_writer.get("files_changed", []))}

## Test Results
✅ {test_runner.get("tests_passed", 0)}/{test_runner.get("total_tests", 0)} tests passed

## Security Audit
{"✅ Passed" if security.get("passed", False) else "❌ Failed"}
{chr(10).join(f"- {f.get('issue', '')}" for f in security.get("findings", []))}

## Original Issue
{issue.get("url", "N/A")}

---
*Generated by SwarmOps — Autonomous DevOps Agent Swarm*
"""

        # Simulate PR URL
        repo_name = repo.get("name", "owner/repo")
        pr_number = 143  # Simulated

        result = {
            "pr_url": f"https://github.com/{repo_name}/pull/{pr_number}",
            "pr_number": pr_number,
            "branch": branch_name,
            "commit_sha": "abc123def456",
            "title": pr_title,
            "description": pr_description,
        }

        self.set_status(AgentStatus.COMPLETED)
        self.confidence = 0.92
        self.output = result

        return self.create_message(
            content=f"✅ Pull Request #{pr_number} opened: {pr_title}\n"
            f"🔗 {result['pr_url']}\n"
            f"📋 Branch: {branch_name}",
            message_type="pr",
            data=result,
        )

    def validate_output(self, output: Dict[str, Any]) -> tuple[bool, str]:
        """Validate PR output."""
        if not output.get("pr_url"):
            return False, "Missing PR URL"

        if not output.get("pr_number"):
            return False, "Missing PR number"

        if not output.get("branch"):
            return False, "Missing branch name"

        if not output.get("title"):
            return False, "Missing PR title"

        return True, ""
