from agents.base import BaseAgent, AgentMessage, AgentStatus
from typing import Dict, Any
from services.llm import get_llm_service
import json


class PROpenerAgent(BaseAgent):
    def __init__(self):
        super().__init__(
            name="pr_opener",
            system_prompt="""You are the PR Opener Agent in SwarmOps.

Your job:
1. Create a feature branch from main/master
2. Apply the code changes
3. Commit with a conventional commit message
4. Open a pull request with detailed description
5. Include test results and security audit in PR body

Rules:
- Use conventional commit format: "fix: description" or "feat: description"
- PR description must include summary, test results, security audit, issue link
- Branch name format: "fix/issue-{number}-description" or "feat/issue-{number}"
- Do NOT merge the PR automatically

Output ONLY valid JSON with no markdown formatting:
{
    "pr_url": "https://github.com/owner/repo/pull/143",
    "pr_number": 143,
    "branch": "fix/issue-42-fix",
    "commit_sha": "abc123",
    "title": "fix: description",
    "description": "Full PR description with sections"
}""",
        )

    async def think(self, context: Dict[str, Any]) -> AgentMessage:
        self.set_status(AgentStatus.THINKING, "Creating pull request")

        issue = context.get("issue", {})
        repo = context.get("repo", {})
        code_writer = context.get("code_writer_output", {})
        test_runner = context.get("test_runner_output", {})
        security = context.get("security_auditor_output", {})

        issue_number = issue.get("number", 0)
        issue_title = issue.get("title", "Fix")
        repo_name = repo.get("name", "owner/repo")

        llm = get_llm_service()
        try:
            raw_output, confidence = llm.chat(
                self.system_prompt,
                {
                    "issue_number": issue_number,
                    "issue_title": issue_title,
                    "issue_url": issue.get("url", ""),
                    "repo_name": repo_name,
                    "code_summary": code_writer.get("summary", ""),
                    "files_changed": code_writer.get("files_changed", []),
                    "test_results": test_runner,
                    "security_results": security,
                },
            )
            raw_output = raw_output.strip()
            if raw_output.startswith("```"):
                raw_output = raw_output.split("\n", 1)[1]
                if "```" in raw_output:
                    raw_output = raw_output.rsplit("```", 1)[0]
            result = json.loads(raw_output)
        except Exception:
            branch_name = f"fix/issue-{issue_number}-swarmops"
            pr_title = f"fix: {issue_title[:50].lower()}"

            description_parts = [
                f"## Summary",
                f"Automated fix for issue #{issue_number}: {issue_title}",
                "",
                f"## Changes",
                code_writer.get("summary", "No summary provided"),
                "",
                f"## Files Modified",
            ]
            for f in code_writer.get("files_changed", []):
                description_parts.append(f"- {f}")
            description_parts += [
                "",
                f"## Test Results",
                f"✅ {test_runner.get('tests_passed', 0)}/{test_runner.get('total_tests', 0)} tests passed",
                "",
                f"## Security Audit",
                "✅ Passed" if security.get("passed", False) else "❌ Failed",
            ]
            for f in security.get("findings", []):
                description_parts.append(f"- {f.get('issue', '')}")
            description_parts += [
                "",
                f"## Original Issue",
                issue.get("url", "N/A"),
                "",
                "---",
                "*Generated by SwarmOps — Autonomous DevOps Agent Swarm*",
            ]

            result = {
                "pr_url": f"https://github.com/{repo_name}/pull/{issue_number}",
                "pr_number": issue_number,
                "branch": branch_name,
                "commit_sha": "abc123def456",
                "title": pr_title,
                "description": "\n".join(description_parts),
            }
            confidence = 0.92

        self.set_status(AgentStatus.COMPLETED)
        self.confidence = confidence
        self.output = result

        return self.create_message(
            content=f"✅ Pull Request #{result['pr_number']} prepared: {result['title']}\n"
            f"🔗 {result['pr_url']}\n"
            f"📋 Branch: {result['branch']}",
            message_type="pr",
            data=result,
        )

    def validate_output(self, output: Dict[str, Any]) -> tuple[bool, str]:
        if not output.get("pr_url"):
            return False, "Missing PR URL"
        if not output.get("pr_number"):
            return False, "Missing PR number"
        if not output.get("branch"):
            return False, "Missing branch name"
        if not output.get("title"):
            return False, "Missing PR title"
        return True, ""
